const D=window.RELIEF_DATA,$=s=>document.querySelector(s);
let absences=[],reliefs=[];
const periods=['7.30 - 8.00','8.00 - 8.30','8.30 - 9.00','9.00 - 9.30','9.30 - 10.00','10.00 - 10.30','10.30 - 11.00','11.00 - 11.30','11.30 - 12.00','12.00 - 12.30','12.30 - 1.00','1.00 - 1.30','1.30 - 2.00','2.00 - 2.30','2.30 - 3.00','3.00 - 3.30','3.30 - 4.00','4.00 - 4.30'];
const savedSettings=JSON.parse(localStorage.getItem('sts_teacher_settings')||'{}');
D.teachers.forEach(t=>{const s=savedSettings[t.id]||{};t.role=s.role||'GURU';t.leave=s.leave||'AKTIF'});
function init(){date.value=new Date().toISOString().slice(0,10);teacherCount.textContent=D.teachers.length;fillAbsent();renderRules();renderTeacherSettings();loadState()}
function getT(id){return D.teachers.find(t=>t.id==id)}
function fillAbsent(){absentSelect.innerHTML='<option value="">-- Pilih guru tidak hadir --</option>'+D.teachers.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}
addAbsent.onclick=()=>{const id=+absentSelect.value;if(id&&!absences.some(a=>a.id===id)){absences.push({id,mode:'ALL',periods:[]});renderAbsences();saveState()}absentSelect.value=''};
function renderAbsences(){absentCount.textContent=absences.length;absentCards.innerHTML=absences.map(a=>{const t=getT(a.id);const taught=(t.schedule[day.value]||[]).map((c,p)=>c?{p,c}:null).filter(Boolean);return `<div class="absenceCard"><div class="absenceTop"><div><b>${t.name}</b><small>${t.short}</small></div><button class="remove" data-rm="${a.id}">×</button></div><div class="absenceMode"><label><input type="radio" name="m${a.id}" data-mode="${a.id}" value="ALL" ${a.mode==='ALL'?'checked':''}> Sepanjang hari</label><label><input type="radio" name="m${a.id}" data-mode="${a.id}" value="PART" ${a.mode==='PART'?'checked':''}> Masa tertentu</label></div>${a.mode==='PART'?`<div class="periodChecks">${taught.length?taught.map(x=>`<label><input type="checkbox" data-period="${a.id}" value="${x.p}" ${a.periods.includes(x.p)?'checked':''}> M${x.p+1}<span>${periods[x.p]||''}</span></label>`).join(''):'<em>Tiada waktu mengajar pada hari ini.</em>'}</div>`:''}</div>`}).join('');
 document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{absences=absences.filter(a=>a.id!=b.dataset.rm);reliefs=[];renderAbsences();renderReliefs();saveState()});
 document.querySelectorAll('[data-mode]').forEach(r=>r.onchange=()=>{const a=absences.find(x=>x.id==r.dataset.mode);a.mode=r.value;a.periods=[];renderAbsences();saveState()});
 document.querySelectorAll('[data-period]').forEach(c=>c.onchange=()=>{const a=absences.find(x=>x.id==c.dataset.period),p=+c.value;a.periods=c.checked?[...new Set([...a.periods,p])]:a.periods.filter(x=>x!==p);saveState()});}
function lessonInfo(code){if(!code)return{subject:'',class:''};return D.subjectMap[code]||{subject:code.split('-')[0]||code,class:code.split('-').slice(1).join('-')}}
function isFree(t,d,p){return !t.schedule[d]?.[p]}
function isolatedGap(t,d,p){const s=t.schedule[d]||[];return p>0&&p<s.length-1&&!!s[p-1]&&!!s[p+1]}
function active(t){return !t.leave||t.leave==='AKTIF'}
function roleOK(t,d,p,assigned){if(!active(t)||t.role==='PENGETUA'||t.role==='GPK_HEM')return false;if(['GPK1','GPK_KOKO','GKMP'].includes(t.role)){if(d==='Isnin'||p<1||p>4||(assigned[t.id]||[]).length>=1)return false}return true}
function score(t,p,assigned){const a=assigned[t.id]||[];const near=a.length?Math.min(...a.map(x=>Math.abs(x-p))):99;const taught=(t.schedule[day.value]||[]).filter(Boolean).length;return a.length*100+(near<3?80:0)+taught}
function generateRelief(){const d=day.value,tasks=[];absences.forEach(a=>{const t=getT(a.id),sched=t.schedule[d]||[];sched.forEach((code,p)=>{if(code&&(a.mode==='ALL'||a.periods.includes(p)))tasks.push({period:p,absentId:a.id,code})})});tasks.sort((a,b)=>a.period-b.period);const assigned={},unavailable=new Set(absences.map(a=>a.id)),out=[];for(const task of tasks){let cand=D.teachers.filter(t=>!unavailable.has(t.id)&&active(t)&&isFree(t,d,task.period)&&!isolatedGap(t,d,task.period)&&roleOK(t,d,task.period,assigned)&&!((assigned[t.id]||[]).some(p=>Math.abs(p-task.period)<3)));cand.sort((a,b)=>score(a,task.period,assigned)-score(b,task.period,assigned)||a.name.localeCompare(b.name));const chosen=cand[0];if(chosen)(assigned[chosen.id]??=[]).push(task.period);out.push({...task,replacementId:chosen?.id||null,note:chosen?'Dijana automatik':'Tiada calon memenuhi syarat'})}reliefs=out;renderReliefs();saveState()}
generate.onclick=generateRelief;
function eligibleOptions(task){return D.teachers.filter(t=>!absences.some(a=>a.id===t.id)&&active(t)&&isFree(t,day.value,task.period)).map(t=>`<option value="${t.id}" ${t.id==task.replacementId?'selected':''}>${t.name} (${roleLabel(t.role)})</option>`).join('')}
function renderReliefs(){reliefCount.textContent=reliefs.length;status.textContent=reliefs.length?`${reliefs.length} waktu relief untuk ${day.value}, ${formatDate(date.value)}.`:'Belum dijana.';reliefBody.innerHTML=reliefs.length?reliefs.map((r,i)=>{const a=getT(r.absentId),li=lessonInfo(r.code),rep=r.replacementId?getT(r.replacementId):null;const repl=manualMode.checked?`<select class="manual-select" data-i="${i}"><option value="">-- Belum ditetapkan --</option>${eligibleOptions(r)}</select>`:(rep?`<b>${rep.name}</b><br><span class="badge">${roleLabel(rep.role)}</span>`:'<span class="badge warn">TIADA CALON</span>');return `<tr><td><b>Masa ${r.period+1}</b><br>${periods[r.period]||''}</td><td>${a.name}</td><td><b>${li.subject}</b><br>${li.class||r.code}</td><td>${repl}</td><td>${r.note||''}</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">Masukkan guru tidak hadir dan tekan “Jana Relief Automatik”.</td></tr>';document.querySelectorAll('.manual-select').forEach(s=>s.onchange=()=>{const i=+s.dataset.i;reliefs[i].replacementId=s.value?+s.value:null;reliefs[i].note='Diubah secara manual';saveState()})}
manualMode.onchange=renderReliefs;preview.onclick=()=>window.print();reset.onclick=()=>{if(confirm('Kosongkan senarai dan jadual relief?')){absences=[];reliefs=[];renderAbsences();renderReliefs();saveState()}};
function roleLabel(r){return({GURU:'Guru',PENGETUA:'Pengetua',GPK1:'GPK 1',GPK_HEM:'GPK HEM',GPK_KOKO:'GPK Kokurikulum',GKMP:'GKMP'})[r]||r}
function leaveLabel(l){return({AKTIF:'Aktif',BERSALIN:'Cuti Bersalin',SEPARUH_GAJI:'Cuti Separuh Gaji',TANPA_GAJI:'Cuti Tanpa Gaji',UMRAH:'Cuti Umrah',HAJI:'Cuti Haji'})[l]||l}
function renderRules(){ruleList.innerHTML=['Pengetua dan GPK HEM tidak boleh menerima relief.','GPK 1, GPK Kokurikulum dan GKMP: maksimum 1 relief, hanya 8.00–10.00 pagi, bukan hari Isnin.','Guru bercuti bersalin, separuh gaji, tanpa gaji, umrah atau haji tidak dipilih.','Guru mestilah bebas dan bukan pada ruang kosong yang diapit dua waktu mengajar.','Sekurang-kurangnya 3 masa antara dua tugasan relief guru yang sama.','Guru tidak hadir boleh dipilih sepanjang hari atau masa tertentu sahaja.','Semua keputusan boleh diubah melalui Mod manual.'].map(x=>`<div class="rule">✓ ${x}</div>`).join('')}
settingsBtn.onclick=()=>settings.showModal();searchTeacher.oninput=renderTeacherSettings;
function renderTeacherSettings(){const q=(searchTeacher?.value||'').toLowerCase();teacherSettings.innerHTML=D.teachers.filter(t=>t.name.toLowerCase().includes(q)||t.short.toLowerCase().includes(q)).map(t=>`<div class="teacherRow"><div><b>${t.name}</b><br><small>${t.short}</small></div><select data-role="${t.id}">${['GURU','PENGETUA','GPK1','GPK_HEM','GPK_KOKO','GKMP'].map(r=>`<option value="${r}" ${t.role===r?'selected':''}>${roleLabel(r)}</option>`).join('')}</select><select data-leave="${t.id}">${['AKTIF','BERSALIN','SEPARUH_GAJI','TANPA_GAJI','UMRAH','HAJI'].map(l=>`<option value="${l}" ${t.leave===l?'selected':''}>${leaveLabel(l)}</option>`).join('')}</select></div>`).join('')}
saveSettings.onclick=e=>{e.preventDefault();document.querySelectorAll('[data-role]').forEach(s=>getT(+s.dataset.role).role=s.value);document.querySelectorAll('[data-leave]').forEach(s=>getT(+s.dataset.leave).leave=s.value);const data={};D.teachers.forEach(t=>data[t.id]={role:t.role,leave:t.leave});localStorage.setItem('sts_teacher_settings',JSON.stringify(data));settings.close();alert('Tetapan guru telah disimpan.')};
function formatDate(v){return v?new Date(v+'T00:00:00').toLocaleDateString('ms-MY',{day:'2-digit',month:'long',year:'numeric'}):''}
day.onchange=()=>{reliefs=[];renderAbsences();renderReliefs();saveState()};date.onchange=saveState;
function saveState(){localStorage.setItem('sts_relief_state_v2',JSON.stringify({date:date.value,day:day.value,absences,reliefs}))}
function loadState(){try{const s=JSON.parse(localStorage.getItem('sts_relief_state_v2'));if(s){date.value=s.date||date.value;day.value=s.day||day.value;absences=s.absences||[];reliefs=s.reliefs||[]}}catch(e){}renderAbsences();renderReliefs()}
init();
