const D=window.RELIEF_DATA, $=s=>document.querySelector(s);let absent=[],reliefs=[];
const periods=['7.30 - 8.00','8.00 - 8.30','8.30 - 9.00','9.00 - 9.30','9.30 - 10.00','10.00 - 10.30','10.30 - 11.00','11.00 - 11.30','11.30 - 12.00','12.00 - 12.30','12.30 - 1.00','1.00 - 1.30','1.30 - 2.00','2.00 - 2.30','2.30 - 3.00','3.00 - 3.30','3.30 - 4.00','4.00 - 4.30'];
const defaultRoles={}; const roles=JSON.parse(localStorage.getItem('sts_roles')||'{}');D.teachers.forEach(t=>t.role=roles[t.id]||defaultRoles[t.id]||'GURU');
function init(){date.value=new Date().toISOString().slice(0,10);teacherCount.textContent=D.teachers.length;fillAbsent();renderRules();renderTeacherSettings();loadState();}
function fillAbsent(){absentSelect.innerHTML='<option value="">-- Pilih guru tidak hadir --</option>'+D.teachers.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}
addAbsent.onclick=()=>{let id=+absentSelect.value;if(id&&!absent.includes(id)){absent.push(id);renderAbsent();saveState()}absentSelect.value=''};
function renderAbsent(){absentChips.innerHTML=absent.map(id=>{let t=getT(id);return `<span class="chip">${t.short}<button data-rm="${id}">×</button></span>`}).join('');absentCount.textContent=absent.length;document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{absent=absent.filter(x=>x!=b.dataset.rm);renderAbsent();saveState()})}
function getT(id){return D.teachers.find(t=>t.id==id)}
function lessonInfo(code){if(!code)return {subject:'',class:''};let m=D.subjectMap[code];if(m)return m;let bits=code.split('-');return {subject:bits[0]||code,class:bits.slice(1).join('-')}}
function isFree(t,day,p){return !t.schedule[day]?.[p]}
function isolatedGap(t,day,p){let s=t.schedule[day]||[];return p>0&&p<s.length-1&&!!s[p-1]&&!!s[p+1]}
function roleOK(t,day,p,assigned){if(t.role==='PENGETUA'||t.role==='GPK_HEM')return false;if(['GPK1','GPK_KOKO','GKMP'].includes(t.role)){if(day==='Isnin')return false;if(p<1||p>4)return false;if((assigned[t.id]||[]).length>=1)return false}return true}
function score(t,p,assigned){let a=assigned[t.id]||[];let dayLoad=a.length;let nearest=a.length?Math.min(...a.map(x=>Math.abs(x-p))):99;let taught=(t.schedule[day.value]||[]).filter(Boolean).length;return dayLoad*100+(nearest<3?80:0)+taught}
function generateRelief(){let dayv=day.value, tasks=[];absent.forEach(id=>{let t=getT(id);(t.schedule[dayv]||[]).forEach((code,p)=>{if(code)tasks.push({period:p,absentId:id,code})})});tasks.sort((a,b)=>a.period-b.period);let assigned={},unavailable=new Set(absent),out=[];for(let task of tasks){let cand=D.teachers.filter(t=>!unavailable.has(t.id)&&isFree(t,dayv,task.period)&&!isolatedGap(t,dayv,task.period)&&roleOK(t,dayv,task.period,assigned)&&!((assigned[t.id]||[]).some(p=>Math.abs(p-task.period)<3)));cand.sort((a,b)=>score(a,task.period,assigned)-score(b,task.period,assigned)||a.name.localeCompare(b.name));let chosen=cand[0];if(chosen)(assigned[chosen.id]??=[]).push(task.period);out.push({...task,replacementId:chosen?.id||null,note:chosen?'Dijana automatik':'Tiada calon memenuhi syarat'})}reliefs=out;renderReliefs();saveState()}
generate.onclick=generateRelief;
function eligibleOptions(task){let dayv=day.value;return D.teachers.filter(t=>!absent.includes(t.id)&&isFree(t,dayv,task.period)).map(t=>`<option value="${t.id}" ${t.id==task.replacementId?'selected':''}>${t.name} (${roleLabel(t.role)})</option>`).join('')}
function renderReliefs(){reliefCount.textContent=reliefs.length;status.textContent=reliefs.length?`${reliefs.length} waktu relief untuk ${day.value}, ${formatDate(date.value)}.`:'Belum dijana.';reliefBody.innerHTML=reliefs.length?reliefs.map((r,i)=>{let a=getT(r.absentId),li=lessonInfo(r.code),rep=r.replacementId?getT(r.replacementId):null;let repl=manualMode.checked?`<select class="manual-select" data-i="${i}"><option value="">-- Belum ditetapkan --</option>${eligibleOptions(r)}</select>`:(rep?`<b>${rep.name}</b><br><span class="badge">${roleLabel(rep.role)}</span>`:'<span class="badge warn">TIADA CALON</span>');return `<tr><td><b>Masa ${r.period+1}</b><br>${periods[r.period]||''}</td><td>${a.name}</td><td><b>${li.subject}</b><br>${li.class||r.code}</td><td>${repl}</td><td>${r.note||''}</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">Masukkan guru tidak hadir dan tekan “Jana Relief Automatik”.</td></tr>';document.querySelectorAll('.manual-select').forEach(s=>s.onchange=()=>{let i=+s.dataset.i;reliefs[i].replacementId=s.value?+s.value:null;reliefs[i].note='Diubah secara manual';saveState()})}
manualMode.onchange=renderReliefs;preview.onclick=()=>window.print();reset.onclick=()=>{if(confirm('Kosongkan senarai guru tidak hadir dan jadual relief?')){absent=[];reliefs=[];renderAbsent();renderReliefs();saveState()}};
function roleLabel(r){return ({GURU:'Guru',PENGETUA:'Pengetua',GPK1:'GPK 1',GPK_HEM:'GPK HEM',GPK_KOKO:'GPK Kokurikulum',GKMP:'GKMP'})[r]||r}
function renderRules(){ruleList.innerHTML=['Pengetua dan GPK HEM dikecualikan sepenuhnya.','GPK 1, GPK Kokurikulum dan GKMP: maksimum 1 relief, hanya 8.00–10.00 pagi, bukan hari Isnin.','Guru mestilah bebas pada waktu berkenaan.','Ruang kosong yang diapit dua waktu mengajar tidak digunakan.','Sekurang-kurangnya 3 masa antara dua tugasan relief guru yang sama.','Agihan mengutamakan guru dengan beban relief paling rendah.','Semua keputusan boleh diubah melalui Mod manual.'].map(x=>`<div class="rule">✓ ${x}</div>`).join('')}
settingsBtn.onclick=()=>settings.showModal();searchTeacher.oninput=renderTeacherSettings;
function renderTeacherSettings(){let q=(searchTeacher?.value||'').toLowerCase();teacherSettings.innerHTML=D.teachers.filter(t=>t.name.toLowerCase().includes(q)||t.short.toLowerCase().includes(q)).map(t=>`<div class="teacherRow"><div><b>${t.name}</b><br><small>${t.short}</small></div><select data-role="${t.id}">${['GURU','PENGETUA','GPK1','GPK_HEM','GPK_KOKO','GKMP'].map(r=>`<option value="${r}" ${t.role===r?'selected':''}>${roleLabel(r)}</option>`).join('')}</select></div>`).join('')}
saveSettings.onclick=e=>{e.preventDefault();document.querySelectorAll('[data-role]').forEach(s=>{let t=getT(+s.dataset.role);t.role=s.value;roles[t.id]=s.value});localStorage.setItem('sts_roles',JSON.stringify(roles));settings.close();renderReliefs();alert('Tetapan peranan telah disimpan.')};
function formatDate(v){if(!v)return'';return new Date(v+'T00:00:00').toLocaleDateString('ms-MY',{day:'2-digit',month:'long',year:'numeric'})}
day.onchange=()=>{reliefs=[];renderReliefs();saveState()};date.onchange=saveState;
function saveState(){localStorage.setItem('sts_relief_state',JSON.stringify({date:date.value,day:day.value,absent,reliefs}))}
function loadState(){try{let s=JSON.parse(localStorage.getItem('sts_relief_state'));if(s){date.value=s.date||date.value;day.value=s.day||day.value;absent=s.absent||[];reliefs=s.reliefs||[]}}catch(e){}renderAbsent();renderReliefs()}
init();
